### ISSUE TITLE
Solved: Error: No Matching function for call to 'aREST::handle(EthernetClient&)'

### ISSUE THREAD

**Issue by TMwL** [marcoschwartz/aREST#31] opened 2015-01-11 15:24 UTC
I tried to compile my code, but this is error keep appearing. I tried it in the IDE 1.5.8 and in the 1.5.7 in a Arduino Mega, and this si what i get:

AM.ino: In function 'void loop()':
AM.ino:49:21: error: no matching function for call to 'aREST::handle(EthernetClient&)'
AM.ino:49:21: note: candidates are:
In file included from AM.ino:1:0:
/Users/ps/Documents/Arduino/libraries/aREST/aREST.h:243:6: note: void aREST::handle(HardwareSerial&)
 void handle(HardwareSerial& serial){
      ^
/Users/ps/Documents/Arduino/libraries/aREST/aREST.h:243:6: note:   no known conversion for argument 1 from 'EthernetClient' to 'HardwareSerial&'
/Users/ps/Documents/Arduino/libraries/aREST/aREST.h:259:6: note: void aREST::handle(char*)
 void handle(char * string) {
      ^
/Users/ps/Documents/Arduino/libraries/aREST/aREST.h:259:6: note:   no known conversion for argument 1 from 'EthernetClient' to 'char*'

What is happening?

**Comment by marcoschwartz** [comment] 2015-01-12 10:47
Hi, thanks for reporting the error. I just tried (using the Ethernet library + Arduino Mega) and I couldn't reproduce the error. I tried with 1.5.7 and 1.5.8  as well. Which operating system are you using?

Also, make sure you are using the latest version of the library, and try to compile from the Ethernet example first and let me know how it goes.

**Comment by TMwL** [comment] 2015-01-12 10:58
Sorry, i sold it by moving the Ethernet.h library call in the top of the sketch, so it identifies the connection type as Ethernet.

**Comment by marcoschwartz** [comment] 2015-01-12 11:12
Good! Closing the issue :)

**Closed by marcoschwartz** 2015-01-12 11:12 UTC
