### ISSUE TITLE
Error when compiling ESP8266.ino

### ISSUE THREAD

**Issue by dogrocker** [marcoschwartz/aREST#43] opened 2015-04-24 10:55 UTC
```
In file included from ESP8266.ino:10:0:
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:879:24: error: '__FlashStringHelper' does not name a type
 void addToBuffer(const __FlashStringHelper *toAdd){
                        ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:879:45: error: ISO C++ forbids declaration of 'toAdd' with no type [-fpermissive]
 void addToBuffer(const __FlashStringHelper *toAdd){
                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'void aREST::send_http_headers()':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:132:188: error: 'F' was not declared in this scope
   addToBuffer(F("HTTP/1.1 200 OK\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: POST, GET, PUT, OPTIONS\r\nContent-Type: application/json\r\nConnection: close\r\n\r\n"));
                                                                                                                                                                                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'bool aREST::send_command(bool)':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:528:40: error: 'F' was not declared in this scope
      Serial.println(F("Sending command"));
                                        ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:545:45: error: 'F' was not declared in this scope
        addToBuffer(F("{\"message\": \"Pin D"));
                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:556:58: error: 'F' was not declared in this scope
       if (!LIGHTWEIGHT){addToBuffer(F(" set to input\", "));}
                                                          ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:566:60: error: 'F' was not declared in this scope
        if (!LIGHTWEIGHT){addToBuffer(F(" set to output\", "));}
                                                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:581:44: error: 'F' was not declared in this scope
         addToBuffer(F("{\"return_value\": "));
                                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:589:44: error: 'F' was not declared in this scope
        if (!LIGHTWEIGHT) {addToBuffer(F("{"));}
                                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:599:29: error: 'F' was not declared in this scope
            addToBuffer(F(","));
                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:602:31: error: 'F' was not declared in this scope
            addToBuffer(F("\"D"));
                               ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:619:46: error: 'F' was not declared in this scope
         addToBuffer(F("{\"message\": \"Pin D"));
                                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:638:44: error: 'F' was not declared in this scope
         addToBuffer(F("{\"return_value\": "));
                                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:645:44: error: 'F' was not declared in this scope
        if (!LIGHTWEIGHT) {addToBuffer(F("{"));}
                                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:655:29: error: 'F' was not declared in this scope
            addToBuffer(F(","));
                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:658:31: error: 'F' was not declared in this scope
            addToBuffer(F("\"A"));
                               ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:673:43: error: 'F' was not declared in this scope
      addToBuffer(F("{\"message\": \"Pin D"));
                                           ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:688:28: error: 'F' was not declared in this scope
         addToBuffer(F("{\""));
                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:720:41: error: 'F' was not declared in this scope
      addToBuffer(F("{\"return_value\": "));
                                         ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:732:40: error: 'F' was not declared in this scope
       addToBuffer(F("{\"variables\": {"));
                                        ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:758:24: error: 'F' was not declared in this scope
       addToBuffer(F("{"));
                        ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:764:26: error: 'F' was not declared in this scope
      addToBuffer(F("\r\n"));
                          ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:769:32: error: 'F' was not declared in this scope
      addToBuffer(F("\"id\": \""));
                                ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:777:51: error: 'F' was not declared in this scope
      Serial.print(F("State of buffer at the end: "));
                                                   ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'void aREST::addToBuffer(char*)':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:839:39: error: 'F' was not declared in this scope
     Serial.print(F("Added to buffer: "));
                                       ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'void aREST::addToBuffer(uint16_t)':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:853:23: error: 'itoa' was not declared in this scope
   itoa(toAdd,number,10);
                       ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'void aREST::addToBuffer(int)':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:862:23: error: 'itoa' was not declared in this scope
   itoa(toAdd,number,10);
                       ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'void aREST::sendBuffer(T&, uint8_t, uint8_t)':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:934:39: error: there are no arguments to 'F' that depend on a template parameter, so a declaration of 'F' must be available [-fpermissive]
         Serial.print(F("Sent buffer: "));
                                       ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:934:39: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
ESP8266.ino: In function 'void setup()':
ESP8266.ino:37:43: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:38:37: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:41:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:44:18: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:45:26: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
In file included from ESP8266.ino:10:0:
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In instantiation of 'void aREST::sendBuffer(T&, uint8_t, uint8_t) [with T = WiFiClient; uint8_t = unsigned char]':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:251:27:   required from here
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:934:39: error: 'F' was not declared in this scope
         Serial.print(F("Sent buffer: "));
                                       ^
Error compiling.
```

I think it is about Arduino ESP8266 IDE doesn't support `__FlashStringHelper` right?

**Comment by marcoschwartz** [comment] 2015-04-28 16:19
It does, just not in the current release unfortunately. Try to get the source & compile it:

$ git clone https://github.com/esp8266/Arduino.git
$ cd Arduino/build
$ ant dist

And let me know if that helps.

**Comment by stephanmarks** [comment] 2015-05-16 12:44
Hi Marco,
I tried your approach but it doesn't change anything
Best wishes
  Stephan

**Comment by marcoschwartz** [comment] 2015-05-16 15:32
Hi Stephan,

I had errors too recently with the latest commits of the ESP8266 Arduino IDE. I released a fix for aREST yesterday, did you already try it ?

Cheers,
Marco

**Comment by stephanmarks** [comment] 2015-05-17 15:57
Hi Marco,

I tried again with the same result. I uses the esp8266 1.6.1 Arduino bundle. I'am not sure witch board should be used. I uses the  Generic ESP Board because the Arduino ESP Board is disabled. 

Best wishes
 Stephan

**Comment by dogrocker** [comment] 2015-05-17 18:08
@marcoschwartz, Thanks for help.

I have test to compile it again with 1.6.1 Arduino IDE with current release (on 5-10 May). and it got only warn message.

```
Build options changed, rebuilding all
In file included from ESP8266.ino:10:0:
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'void aREST::send_http_headers()':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:129:189: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   addToBuffer(F("HTTP/1.1 200 OK\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Methods: POST, GET, PUT, OPTIONS\r\nContent-Type: application/json\r\nConnection: close\r\n\r\n"));
                                                                                                                                                                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h: In member function 'bool aREST::send_command(bool)':
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:574:46: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
        addToBuffer(F("{\"message\": \"Pin D"));
                                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:585:59: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
       if (!LIGHTWEIGHT){addToBuffer(F(" set to input\", "));}
                                                           ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:595:61: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
        if (!LIGHTWEIGHT){addToBuffer(F(" set to output\", "));}
                                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:610:45: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("{\"return_value\": "));
                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:612:28: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F(", "));
                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:618:45: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
        if (!LIGHTWEIGHT) {addToBuffer(F("{"));}
                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:628:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F(","));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:631:32: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F("\"D"));
                                ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:633:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F("\": "));
                                 ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:635:31: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F(", "));
                               ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:648:47: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("{\"message\": \"Pin D"));
                                               ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:650:34: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F(" set to "));
                                  ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:652:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("\", "));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:667:45: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("{\"return_value\": "));
                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:669:28: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F(", "));
                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:674:45: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
        if (!LIGHTWEIGHT) {addToBuffer(F("{"));}
                                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:684:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F(","));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:687:32: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F("\"A"));
                                ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:689:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F("\": "));
                                 ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:691:31: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
            addToBuffer(F(", "));
                               ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:702:44: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F("{\"message\": \"Pin D"));
                                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:704:31: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F(" set to "));
                               ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:706:27: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F("\", "));
                           ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:717:29: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("{\""));
                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:719:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("\": "));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:721:28: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F(", ")); 
                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:732:29: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("{\""));
                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:734:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("\": "));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:736:28: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F(", ")); 
                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:748:29: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("{\""));
                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:750:32: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("\": \""));
                                ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:752:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("\", ")); 
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:765:42: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F("{\"return_value\": "));
                                          ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:767:25: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F(", "));
                         ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:777:41: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
       addToBuffer(F("{\"variables\": {"));
                                         ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:783:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
           addToBuffer(F("\""));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:785:32: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
           addToBuffer(F("\": "));
                                ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:787:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
           addToBuffer(F(", "));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:789:28: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("\""));
                            ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:791:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("\": "));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:793:29: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F("}, "));
                             ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:796:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
         addToBuffer(F(" }, "));
                              ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:805:25: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
       addToBuffer(F("{"));
                         ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:811:27: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F("\r\n"));
                           ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:816:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F("\"id\": \""));
                                 ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:818:39: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F("\", \"name\": \""));
                                       ^
/Users/Kanin/Documents/Arduino/libraries/aREST/aREST.h:820:51: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
      addToBuffer(F("\", \"connected\": true}\r\n"));
                                                   ^
ESP8266.ino: In function 'void setup()':
ESP8266.ino:37:43: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:38:37: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:41:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:44:18: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:45:26: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

Sketch uses 242,129 bytes (46%) of program storage space. Maximum is 524,288 bytes.
```

but I will try soon with 1.6.4

**Comment by dogrocker** [comment] 2015-05-17 18:09
@stephanmarks, Did you compile Arduino IDE to the lasted release?

**Comment by marcoschwartz** [comment] 2015-05-18 08:08
Yes, I got warning messages too :) With recent versions of the ESP8266 Arduino IDE I had errors as well, but I updated aREST to remove theses errors (also linked to PROGMEM). I can confirm that with the latest version from the source + latest aREST version it compiles fine.

**Comment by aniston** [comment] 2015-05-18 22:23
Hello Marco,
I too am getting compile errors with the ESP8266 example, unfortunately my setup is far from standard, but if it helps here is the senario:
W7x64 + ESP8266 Arduino add-on from Sandeepmistry (on Arduino 1.6.4) + aREST 1.9.8
I might add that many other programs compile and build well but I'm not sure if I'm doing this the right way !

Any suggestions ?

```
Using library ESP8266WiFi in folder: U:\ARDUINO\Arduino_1.6.4\hardware\esp8266com\esp8266\libraries\ESP8266WiFi 
Using library aREST in folder: U:\ARDUINO\SKETCHES\libraries\aREST-1.9.8 

U:\ARDUINO\Arduino_1.6.4\hardware\esp8266com/esp8266/tools/windows/xtensa-lx106-elf/bin/xtensa-lx106-elf-g++ -D__ets__ -DICACHE_FLASH -U__STRICT_ANSI__ -IU:\ARDUINO\Arduino_1.6.4\hardware\esp8266com/esp8266/sdk//include -c -Os -mlongcalls -mtext-section-literals -fno-exceptions -fno-rtti -std=c++11 -MMD -DF_CPU=80000000L -DARDUINO=10604 -DARDUINO_ESP8266_ESP01 -DARDUINO_ARCH_ESP8266 -DESP8266 -IU:\ARDUINO\Arduino_1.6.4\hardware\esp8266com\esp8266\cores\esp8266 -IU:\ARDUINO\Arduino_1.6.4\hardware\esp8266com\esp8266\variants\generic -IU:\ARDUINO\Arduino_1.6.4\hardware\esp8266com\esp8266\libraries\ESP8266WiFi\src -IU:\ARDUINO\SKETCHES\libraries\aREST-1.9.8 C:\Users\aniston\AppData\Local\Temp\build5102094768893817726.tmp\ESP_aREST_20150518.cpp -o C:\Users\aniston\AppData\Local\Temp\build5102094768893817726.tmp\ESP_aREST_20150518.cpp.o
```
regards,
aniston.

**Comment by marcoschwartz** [comment] 2015-05-19 07:52
Hi all! Well, since last night there might be some news that could help everybody :) Check on:

https://github.com/esp8266/Arduino

Basically there is now a way to use the official Arduino IDE (1.6.4) and just use the board manager. The instructions are:

Starting with 1.6.4, Arduino allows installation of third-party platform packages using Boards Manager. We have packages available for Windows, Mac OS, and Linux (32 and 64 bit).

Install Arduino 1.6.4 from the Arduino website.
Start Arduino and open Perferences window.
Enter http://arduino.esp8266.com/package_esp8266com_index.json into Additional Board Manager URLs field. You can add multiple URLs, separating them with commas.
Open Boards Manager from Tools > Board menu and install esp8266 platform (and don't forget to select your ESP8266 board from Tools > Board menu after installation).

I haven't tried it myself yet, but I will do today and if it works I will recommend that as the way to use aREST as it doesn't required to build Arduino from scratch.

**Comment by stephanmarks** [comment] 2015-05-27 17:04
Hi
sorry for the delay. 

I have tested the new Version 1.6.4 with the instruction from Marco. All works well but while the transfer I get this error

warning: espcomm_sync failed
error: espcomm_open failed

I have checked my wiring but I can see any mistake. I am using the ESP 01 Board. 

![bildschirmfoto vom 2015-05-27 19 02 57](https://cloud.githubusercontent.com/assets/10739316/7842378/0728dcf6-04a3-11e5-813f-71cf7a76bab0.png)

Best wishes 
  Stephan

**Comment by marcoschwartz** [comment] 2015-05-27 17:26
Looks like the board is not in bootloader mode. Can you try by following these instructions (from my website):

After that, we need to put the board in bootloader mode, so we can program it. To do so, connect the pin GPIO 0 to the ground, via the cable we plugged into GPIO 0 before. Then, power cycle the board but switching the power supply off & then on again.

Now, upload the code to the board, and open the Serial monitor when this is done. Also set the Serial monitor speed to 115200. Now, disconnect the cable between GPIO 0 and GND, and power cycle the board again. You should see the following message:

**Comment by probonopd** [comment] 2015-07-13 19:06
I compiled https://github.com/esp8266/Arduino from git. Compilation of the ESP8266 demo sketch gives

```
ESP8266.cpp.o 
In file included from ESP8266.ino:10:0:
/Users/user/Documents/Arduino/libraries/aREST/aREST.h: In member function 'void aREST::addToBuffer(const __FlashStringHelper*)':
/Users/user/Documents/Arduino/libraries/aREST/aREST.h:884:23: error: section attribute cannot be specified for local variables
   const char PROGMEM *p = (const char PROGMEM *)toAdd;
                       ^
/Users/user/Documents/Arduino/libraries/aREST/aREST.h:884:47: warning: 'section' attribute does not apply to types [-Wattributes]
   const char PROGMEM *p = (const char PROGMEM *)toAdd;
                                               ^
ESP8266.ino: In function 'void setup()':
ESP8266.ino:37:43: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:38:37: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:41:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:44:18: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
ESP8266.ino:45:26: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
Error compiling.
```

**Comment by marcoschwartz** [comment] 2015-07-15 10:24
Hello,

For the latest version of aREST you need to use the built-in library manager from the Arduino IDE. I will update the README soon, in the meantime refer to: https://github.com/esp8266/Arduino

**Comment by marcoschwartz** [comment] 2015-08-27 12:48
Closing this issue as it works fine with latest version of Arduino with the board manager.

**Closed by marcoschwartz** 2015-08-27 12:48 UTC

**Comment by suezz** [comment] 2015-09-01 19:29
deprecated conversion warning...ide 1.6.5..

**Comment by marcoschwartz** [comment] 2015-09-02 12:45
Well warnings doesn't prevent the library to work :) Are you sure it doesn't work properly ?

**Comment by suezz** [comment] 2015-09-04 18:36
sorry, yes it does ... but only rest.button seem to work(esp8266 example), keep experimentation...:)
