### ISSUE TITLE
Compilation Error:  conversion from 'String' to 'char*'

### ISSUE THREAD

**Issue by dextergiii** [marcoschwartz/aREST#27] opened 2014-11-12 04:40 UTC
Hello, 

I am currently working from the  Arduino Home Automation Projects book in chapter 1.  When I load the following code, I get a compilation error as shown below:

I'm using the IDE 1.5.8 if that helps. Thank you for any guidance.  

Code:
// Libraries
#include <SPI.h>
#include <aREST.h>

// Motion sensor ID
String xbee_id = "2";

// Create ArduREST instance
aREST rest = aREST();

void setup() {
  
  // Start Serial
  Serial.begin(9600);
  
  // Give name and ID to device
  rest.set_id(xbee_id);
}

void loop() {
  
  // Handle REST calls
  rest.handle(Serial);
  
}

Error Message:  
HomeAuto_Chap1_RevA.ino.ino: In function 'void setup()':
HomeAuto_Chap1_RevA.ino.ino:17:22: error: no matching function for call to 'aREST::set_id(String&)'
HomeAuto_Chap1_RevA.ino.ino:17:22: note: candidate is:
In file included from HomeAuto_Chap1_RevA.ino.ino:3:0:
E:\Documents\Arduino\Sketches\libraries\aREST/aREST.h:714:6: note: void aREST::set_id(char*)
 void set_id(char *device_id){
      ^
E:\Documents\Arduino\Sketches\libraries\aREST/aREST.h:714:6: note:   no known conversion for argument 1 from 'String' to 'char*'
Error compiling.

**Comment by russbrookes** [comment] 2015-01-18 20:50
I had the same problem with the serial output of /digital/8/r when using rest.handle(Serial) not showing the first part of the expected output.  ie ..
expected: {return_value": 0, "id": "2", "name": "", "connected": true}
actual: "id": "2", "name": "", "connected": true}

Thanks, dextergiii, for the direction above to set the Arduino IDE serial monitor to "carriage return" instead of "no line ending" in the bottom right corner (just to the left of baud rate setting).  That solved the problem.

**Comment by russbrookes** [comment] 2015-01-19 01:50
Hi Marco,
  I'm attempting to "Building Wireless XBee Motion Detectors" from your book Arduino Home Automation Projects. I'm using a Windows machine for my EasyPHP webserver, and have an XBee module plugged into the USB port of that machine.  It appears as COM13.  I've changed the line in XBee.php from $serial_port = "/dev/cu.usbserial-A702LF8B" to $serial_port="COM13", but the coloured block for Sensor 2 does not change colour (I already confirmed by PIR sensor is working and can read if connected DLINE on Arduino and use /digital/8/r command).  Any advice?

**Comment by marcoschwartz** [comment] 2015-01-25 16:46
Hi there, that should work fine, as you are doing the right thing for the serial port. Can you try to directly plug your Arduino board to the USB port & then use the Serial port corresponding to the USB port instead of the XBee one? Then we'll know if the issue is coming from the XBee module or the code.

**Comment by russbrookes** [comment] 2015-01-25 19:37
Thanks. I think I figured it out. I'm using Windows and the php_serial.class.php code is buggy for Windows (it actually has that comment in the code). Using XCTU I can connect the PC to the xbee and have it wirelessly communicate to the other Xbee attached to the arduino. When I send the "/digital/8/r" and a hex 0D string to the port using XCTU the arduino responds every time exactly as expected, even if I do it as fast as every 100ms.

  The problem with xbee.php is that it uses php_serial.class.php, which uses the DOS/Windows MODE command, to set each parameter of the port individually. For example it uses mode to set just the baud rate, then it calls mode again to set just  the parity, then it uses mode again to set just the number of data bits, parity, etc..  The problem with this approach is that using the dos/windows MODE command with just one parameter causes it to reset some other parameters back to their default parameters.  For example if you set parity to none it will automatically set data bits back to 7 even if you had previously called MODE to set the port to 8 data bits. At first I thought I'd just switch the order of setting the port parameters. But due to the fact that multiple parameters when set individually reset some other parameter back to a default, there is no reliable order I could find  in which you could set the parameters individually and still end up with 9600, 8, n, 1, xon=off, RTS off, CTS off and to=off. 

So what was happening is that by chance with bad port settings sometimes on a read from serial port it would get some characters that were recognizable to xbee.php and Java.js, and it would seem to work. But it was completely random and could happen within a few seconds or 30 seconds or never. 

The other problem with the way the the program works is that the port baud rate etc. settings were being set every time Java.js requested a read from the port and Xbee was having to call php_serial.class.php multiple times - once for each port setting (baud, data, parity, etc.)

And since accessing MODE from php can take 1 to 3 seconds every time -  these delays were adding up and making it so that under even the best circumstances the info from the sensor attached to the arduino would only be read and transferred back to the web page every 5 to 10 seconds. (And of course each time had garbled characters)

The third problem I found was that the return value I got when the sensor detected motion was 0, but Java.js was turning Sensor 2 indicator Gray if it got a 0, instead of orange. 

I might get some time to day to write some some code to handle the serial port more efficiently. 

This is the first time I've ever encountered or done any JavaScript or php programming - so this has been quite a learning opportunity for me. I've enjoyed it very much.

**Closed** 2015-04-03 19:59 UTC
