### ISSUE TITLE
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds

### ISSUE THREAD

**Issue by Noobz347** [marcoschwartz/aREST#214] opened 2018-02-27 15:06 UTC
HI!,
I keep getting this message from the serial monitor
"Attempting MQTT connection...failed, rc=-2 try again in 5 seconds"

I am using the Huzzah Feather.  I have all three of the libraries installed and updated.  I have internet connectivity.  I've tried different device names. and successfully pinged aREST from a computer on the same network.

From Serial Monitor:

.....
WiFi connected
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, r..................

Any assistance would be appreciated and Thank You in advance.  :)

~Noobz

The code is loaded as follows with exception of network credentials:

// Control ESP8266 anywhere

// Import required libraries
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <aREST.h>

// Clients
WiFiClient espClient;
PubSubClient client(espClient);

// Create aREST instance
aREST rest = aREST(client);

// Unique ID to identify the device for cloud.arest.io
char* device_id = "Fg3yz3";

// WiFi parameters
const char* ssid = "zzzzzzzzzz";
const char* password = "zzzzzzzzzz";

// Functions
void callback(char* topic, byte* payload, unsigned int length);

void setup(void)
{
  // Start Serial
  Serial.begin(115200);

  // Set callback
  client.setCallback(callback);
  
  // Give name and ID to device
  rest.set_id(device_id);
  rest.set_name("relay_anywhere");

  // Connect to WiFi
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");

  // Set output topic
  char* out_topic = rest.get_topic();

}

void loop() {

  // Connect to the cloud
  rest.loop(client);

}

// Handles message arrived on subscribed topic(s)
void callback(char* topic, byte* payload, unsigned int length) {

  rest.handle_callback(client, topic, payload, length);

}

**Comment by Noobz347** [comment] 2018-02-28 19:26
ping

**Comment by WioSwitch** [comment] 2018-02-28 22:34
try change char* device_id = "Fg3yz3";
to const char* device_id = "newid";

**Comment by WioSwitch** [comment] 2018-02-28 22:38
Add:

// The port to listen for incoming TCP connections
#define LISTEN_PORT           80

**Comment by WioSwitch** [comment] 2018-02-28 22:50
/*
  This a simple example of the aREST Library for the ESP8266 WiFi chip.
  This example illustrate the cloud part of aREST that makes the board accessible from anywhere
  See the README file for more details.

  Written in 2015 by Marco Schwartz under a GPL license.
*/

// Import required libraries
#include <ESP8266WiFi.h>
#include <PubSubClient.h>
#include <aREST.h>

// Clients
WiFiClient espClient;
PubSubClient client(espClient);

// Create aREST instance
aREST rest = aREST(client);

// Unique ID to identify the device for cloud.arest.io
const char* device_id = "Fg3yz3";

// WiFi parameters
const char* ssid = "zzzzzzzzzz";
const char* password = "zzzzzzzzzz";

// Variables to be exposed to the API
int temperature;
int humidity;
String local_ip = "";

// The port to listen for incoming TCP connections
#define LISTEN_PORT           80

// Create an instance of the server
WiFiServer server(LISTEN_PORT);

// Functions
void callback(char* topic, byte* payload, unsigned int length);

void setup(void)
{
  // Start Serial
  Serial.begin(115200);

  // Set callback
  client.setCallback(callback);

  // Init variables and expose them to REST API
  temperature = 24;
  humidity = 40;
  rest.variable("temperature", &temperature);
  rest.variable("humidity", &humidity);
  rest.variable("local_ip", &local_ip);

  // Give name & ID to the device (ID should be 6 characters long)
  rest.set_id(device_id);
  rest.set_name("esp8266");

  // Connect to WiFi
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");

  // Start the server
  server.begin();
  Serial.println("Local server started on IP:");

  // Print the IP address
  Serial.println(WiFi.localIP());
  local_ip = ipToString(WiFi.localIP());

}

void loop() {

  // Connect to the cloud
  rest.handle(client);

  // Handle Local aREST calls
  WiFiClient clientLocal = server.available();
  if (!clientLocal) {
    return;
  }
  while(!clientLocal.available()){
    delay(1);
  }
  rest.handle(clientLocal);

}

// Handles message arrived on subscribed topic(s)
void callback(char* topic, byte* payload, unsigned int length) {

  rest.handle_callback(client, topic, payload, length);

}

// Convert IP address to String
String ipToString(IPAddress address)
{
  return String(address[0]) + "." +
    String(address[1]) + "." +
    String(address[2]) + "." +
    String(address[3]);
}

**Comment by marcoschwartz** [comment] 2018-03-01 03:36
Hi, are you still having the issue? I can confirm on my side that the cloud server is working fine :)

**Comment by Noobz347** [comment] 2018-03-01 20:27
Thank you for the responses.  I will try these things and report back.  :)

**Comment by Noobz347** [comment] 2018-03-01 20:37
I still have the same result:


WiFi connected
Local server started on IP:
172.16.1.232
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...


I am beginning to suspect a hardware issue?

**Comment by marcoschwartz** [comment] 2018-03-11 13:07
Maybe... what hardware do you use in your example? 

Also make sure to use the latest version of aREST - maybe it is trying to connect to the wrong server.

**Comment by Noobz347** [comment] 2018-03-12 18:28
It's a Feather Huzzah ESP8266 WiFi
4MB Flash
80MHz
3.3V

**Comment by WioSwitch** [comment] 2018-03-12 22:11
Your device IP is 172.16.1.232, so how many device you have at home/office?

Push the reset button on your board and if it still not working unplug your router if you can and then plug in and let your router do it stuff.

**Comment by marcos2069** [comment] 2018-12-15 22:36
The connection to my MQTT broker on a raspberry worked for months... probably after an upgrade it started to fail, but not always... just most of the time. The solution for me was to move to broker from wireless to wired. Now using the wired-ip it works, on the wireless-ip most of time not!

**Comment by xEvheMary** [comment] 2019-06-10 18:16
If you're still having this issue
try to disable the static ip address
it works for me

**Comment by DeepMuru** [comment] 2019-07-01 02:03
> HI!,
> I keep getting this message from the serial monitor
> "Attempting MQTT connection...failed, rc=-2 try again in 5 seconds"
> 
> I am using the Huzzah Feather. I have all three of the libraries installed and updated. I have internet connectivity. I've tried different device names. and successfully pinged aREST from a computer on the same network.
> 
> From Serial Monitor:
> 
> .....
> WiFi connected
> Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
> Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
> Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
> Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
> Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
> Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
> Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
> Attempting MQTT connection...failed, r..................
> 
> Any assistance would be appreciated and Thank You in advance. :)
> 
> ~Noobz
> 
> The code is loaded as follows with exception of network credentials:
> 
> // Control ESP8266 anywhere
> 
> // Import required libraries
> #include <ESP8266WiFi.h>
> #include <PubSubClient.h>
> #include <aREST.h>
> 
> // Clients
> WiFiClient espClient;
> PubSubClient client(espClient);
> 
> // Create aREST instance
> aREST rest = aREST(client);
> 
> // Unique ID to identify the device for cloud.arest.io
> char* device_id = "Fg3yz3";
> 
> // WiFi parameters
> const char* ssid = "zzzzzzzzzz";
> const char* password = "zzzzzzzzzz";
> 
> // Functions
> void callback(char* topic, byte* payload, unsigned int length);
> 
> void setup(void)
> {
> // Start Serial
> Serial.begin(115200);
> 
> // Set callback
> client.setCallback(callback);
> 
> // Give name and ID to device
> rest.set_id(device_id);
> rest.set_name("relay_anywhere");
> 
> // Connect to WiFi
> WiFi.begin(ssid, password);
> while (WiFi.status() != WL_CONNECTED) {
> delay(500);
> Serial.print(".");
> }
> Serial.println("");
> Serial.println("WiFi connected");
> 
> // Set output topic
> char* out_topic = rest.get_topic();
> 
> }
> 
> void loop() {
> 
> // Connect to the cloud
> rest.loop(client);
> 
> }
> 
> // Handles message arrived on subscribed topic(s)
> void callback(char* topic, byte* payload, unsigned int length) {
> 
> rest.handle_callback(client, topic, payload, length);
> 
> }

**Comment by DeepMuru** [comment] 2019-07-01 02:04
hiii im getting the same problem what @Noobz347 
please help me to solve it

**Comment by jPerotto** [comment] 2019-07-02 19:23
Hi @DeepMuru 

I was having the same problem, however I suspected of my Wi-Fi connection, I switched from Wi-Fi using the host of my smartphone and it worked.
I'll check the code to see if I find any inconsistency in using the connection to the protocol.

**Comment by clsatw** [comment] 2019-08-03 04:05
the same error here. it was working 1 year ago but somehow gets the error. 
i'm using nodemcu ver 1.

**Comment by clsatw** [comment] 2019-08-03 04:28
it is working now after i recompile and upload from arduino ide.

**Comment by manuelfgm** [comment] 2020-02-19 22:16
I left this comment in other thread to solve this issue in my case: https://github.com/knolleary/pubsubclient/issues/604#issuecomment-588495411

**Comment by Pi-And-More** [comment] 2020-03-20 21:13
I had the same issues and it was driving me mad because I had it working and after delivering a few working devices (and of course updating my code) it stopped working. I finally figured it out. I changed the mqttServer from a DNS name to an IP. This is what broke it. I just changed it back to a server name that can resolve on DNS without changing anything else and the error disappeared.

**Comment by csshull** [comment] 2020-09-11 13:43
I had the same error.  It worked ok at first and then starting having problems reconnecting.  My problem was I had the IP address of the NodeMCU assigned to a specific MAC address, which was ok but I had the same MAC address assigned to two different IP addresses.  I removed the duplicate assignment in the router and all is working well. Note: I didn't think the router configuration (TP-Link 5400) would allow the duplication but it was configurated that way.

**Comment by zsmartrango** [comment] 2020-12-16 11:02
client.connect("arduinoClient", "YUOR_LOGIN", "YOUR_PASSWORD") it help me to connect to broker

**Comment by AaronShawSF** [comment] 2021-02-15 21:42
Hi I am trying to use the autoconnect wifi code with it. I am having the same issue can you please tell me where the issue is
`#include <WiFi.h>
#include "SPIFFS.h"
#include <WiFiClientSecure.h>
#include <PubSubClient.h>
#include <WebServer.h>
#include <AutoConnect.h>
const int PushButton = 15;
int LEDPIN = 2;
WebServer Server;
AutoConnect Portal(Server);

const char* mqtt_server = "https://**.us-east-2.amazonaws.com/"; // Relace with your MQTT END point
const int mqtt_port = 8883;

String Read_rootca;
String Read_cert;
String Read_privatekey;

//=============================================================================================================================
#define BUFFER_LEN  256
long lastMsg = 0;
char msg[BUFFER_LEN];
int value = 0;
byte mac[6];
char mac_Id[18];
int count = 1;
//=============================================================================================================================


WiFiClientSecure espClient;
PubSubClient client(espClient);

void setup_wifi() {
  delay(10);
  Serial.println();
  Serial.print("Connecting to ");

//   while (WiFi.status() != WL_CONNECTED) {
//    delay(500);
//    Serial.print(".");
//    Portal.handleClient();
//  }
    Server.on("/", rootPage);
  if (Portal.begin()) {
    Serial.println("HTTP server:" + WiFi.localIP().toString());
  }

  randomSeed(micros());

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
}


void rootPage() {
    char content[] = "I am Iron Man ";
    Server.send(200, "text/plain", content);

}

void callback(char* topic, byte* payload, unsigned int length) {
  Serial.print("Message arrived [");
  Serial.print(topic);
  Serial.print("] ");
  for (int i = 0; i < length; i++) {
    Serial.print((char)payload[i]);
  }
  Serial.println();
}
void reconnect() {
  // Loop until we're reconnected
  while (!client.connected()) {
    Serial.print("Attempting MQTT connection...");
    // Create a random client ID
    String clientId = "ESP32-";
    clientId += String(random(0xffff), HEX);
    // Attempt to connect
    if (client.connect(clientId.c_str())) {
      Serial.println("connected");
      // Once connected, publish an announcement...
      client.publish("ei_out", "hello world");
      // ... and resubscribe
      client.subscribe("ei_in");
    } else {
      Serial.print("failed, rc=");
      Serial.print(client.state());
      Serial.println(" try again in 5 seconds");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}




void setup() {
  delay(1000);
  Serial.begin(115200);
  Serial.println();
  
  pinMode(LEDPIN, OUTPUT);
  pinMode(PushButton, INPUT);
  setup_wifi();

  //=============================================================
  if (!SPIFFS.begin(true)) {
    Serial.println("An Error has occurred while mounting SPIFFS");
    return;
  }
  //=======================================
  //Root CA File Reading.
  File file2 = SPIFFS.open("/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem", "r");
  if (!file2) {
    Serial.println("Failed to open file for reading");
    return;
  }
  Serial.println("Root CA File Content:");
  while (file2.available()) {
    Read_rootca = file2.readString();
    Serial.println(Read_rootca);
  }
  //=============================================
  // Cert file reading
  File file4 = SPIFFS.open("/3992c99899-certificate.pem.crt", "r");
  if (!file4) {
    Serial.println("Failed to open file for reading");
    return;
  }
  Serial.println("Cert File Content:");
  while (file4.available()) {
    Read_cert = file4.readString();
    Serial.println(Read_cert);
  }
  //=================================================
  //Privatekey file reading
  File file6 = SPIFFS.open("/3992c99899-private.pem.key", "r");
  if (!file6) {
    Serial.println("Failed to open file for reading");
    return;
  }
  Serial.println("privateKey File Content:");
  while (file6.available()) {
    Read_privatekey = file6.readString();
    Serial.println(Read_privatekey);
  }
  //=====================================================

  char* pRead_rootca;
  pRead_rootca = (char *)malloc(sizeof(char) * (Read_rootca.length() + 1));
  strcpy(pRead_rootca, Read_rootca.c_str());

  char* pRead_cert;
  pRead_cert = (char *)malloc(sizeof(char) * (Read_cert.length() + 1));
  strcpy(pRead_cert, Read_cert.c_str());

  char* pRead_privatekey;
  pRead_privatekey = (char *)malloc(sizeof(char) * (Read_privatekey.length() + 1));
  strcpy(pRead_privatekey, Read_privatekey.c_str());

  Serial.println("================================================================================================");
  Serial.println("Certificates that passing to espClient Method");
  Serial.println();
  Serial.println("Root CA:");
  Serial.write(pRead_rootca);
  Serial.println("================================================================================================");
  Serial.println();
  Serial.println("Cert:");
  Serial.write(pRead_cert);
  Serial.println("================================================================================================");
  Serial.println();
  Serial.println("privateKey:");
  Serial.write(pRead_privatekey);
  Serial.println("================================================================================================");

  espClient.setCACert(pRead_rootca);
  espClient.setCertificate(pRead_cert);
  espClient.setPrivateKey(pRead_privatekey);

  client.setServer(mqtt_server, mqtt_port);
  client.setCallback(callback);

  //====================================================================================================================
  WiFi.macAddress(mac);
  snprintf(mac_Id, sizeof(mac_Id), "%02x:%02x:%02x:%02x:%02x:%02x",
           mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
  Serial.print(mac_Id);
  //=====================================================================================================================

  
  delay(2000);
}

void loop() {
    
  Portal.handleClient();
int Push_button_state = digitalRead(PushButton);
int sanitizer = 0;

if ( Push_button_state == HIGH ){ 
  digitalWrite(LEDPIN, HIGH); 
  sanitizer = 15;
  Serial.println(" LED HIGH");
}else {
  digitalWrite(LEDPIN, LOW); 
  sanitizer = 100;
  Serial.println("LED LOW");
  }

if (!client.connected()) {
    reconnect();
  }
  client.loop();

  long now = millis();
  if (now - lastMsg > 2000) {
    lastMsg = now;
    //=============================================================================================
    String macIdStr = mac_Id;
    snprintf (msg, BUFFER_LEN, "{\"topic\":\"inventory\",\"oz_rem\":\"%s\",\"par\":\"%s\",\"low_lvl\":\"%s\",\"empty_lvl\":\"%s\",\"ts\":\"2021-02-11T21:35:45Z\",\"mid\":\"TEST0001\",\"gp\":\"GPR1\",\"sgp\":\"SGRP1A\"}",String(sanitizer),String(sanitizer),String(sanitizer),String(sanitizer));
    Serial.print("Publish message: ");
    Serial.print(count);
    Serial.println(msg);
    client.publish("ei_out", msg);
    count = count + 1;
    //================================================================================================
  }
  digitalWrite(2, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(2, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second


}

    
`

**Comment by marcoschwartz** [comment] 2021-05-21 06:32
Hello, sorry for the late answer on this! We had some issues with the aREST cloud in the past months but now it is all fixed :) We also have created a quick start guide to help you connect your devices to the aREST cloud server: https://arest.io/quick-start. Hope that helps!

**Closed by marcoschwartz** 2021-05-21 06:32 UTC

**Comment by jinal17patel** [comment] 2023-11-05 07:39
Hello
I keep getting  this message from the serial monitor 
"Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds"
 
I am using my MQTT broker app and for program  I am using Arduino IDE. I have also all libraries installed and updatted.
so what is the solution for this problem. Plz help me..

**Comment by ghost** [comment] 2023-11-05 07:40
Hello
I keep getting this message from the serial monitor
"Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds
Attempting MQTT connection...failed, rc=-2 try again in 5 seconds"

I am using my MQTT broker app and for program I am using Arduino IDE. I have also all libraries installed and updated.
so what is the solution for this problem. Plz help me..
