### ISSUE TITLE
function String params not properly terminated

### ISSUE THREAD

**Issue by ToSa27** [marcoschwartz/aREST#39] opened 2015-04-13 10:09 UTC
The String provided as parameter to a called function is not terminated appropriately. Just printing the same includes the trailing "HTTP" characters from the http request. The Length() function provides the incorrect length as well. In addition it seems like the name of the query parameter is not checked but is just skipped so that with shorter (or omitting the name completely) results get scrambled as well:

Examples:
http://10.0.1.130/text?params=hallo
prints as "hallo HTTP"
http://10.0.1.130/text?text=hallo
prints as "llo HTTP"
http://10.0.1.130/text?hallo
prints as "TTP"

**Comment by marcoschwartz** [comment] 2015-04-14 07:51
Thanks for letting me know! I'll have a look at your pull request.

**Comment by michaelsproul** [comment] 2015-05-27 07:00
I ran into this too.

**Comment by marcoschwartz** [comment] 2015-05-27 07:40
I just tested that, it works just fine. I tried:

http://10.0.1.130/text?params=hallo

And the returned parameters is 'hallo'. Can you give more details like which hardware you are using? And also which Arduino IDE version? This way I can try to isolate the issue. Thanks!

**Comment by michaelsproul** [comment] 2015-05-28 00:22
I'm running a [Freetronics TwentyTen][2010], which is Arduino Duemilanove compatible. I'm using a standard WizNet Ethernet 5100 shield and version 1.6.4 of the Arduino IDE (which is stable).

Here's a minimal example that shows the bug:

```arduino
#include <SPI.h>
#include <Ethernet.h>
#include <aREST.h>

byte mac[] = { 0x00, 0x00, 0xDE, 0xAD, 0xBE, 0xEF };

IPAddress ip(192,168,2,2);

EthernetServer server(80);

aREST rest = aREST();

void setup(void) {
  Serial.begin(9600);

  rest.set_id("001");
  rest.set_name("test");
  rest.function("print", printHandler);

  // Start the Ethernet connection and the server
  if (Ethernet.begin(mac) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // Try to congifure using IP address instead of DHCP:
    Ethernet.begin(mac, ip);
  }
  server.begin();
  Serial.print("Server: ");
  Serial.println(Ethernet.localIP());
}

void loop() {
  EthernetClient client = server.available();
  rest.handle(client);
}

int printHandler(String command) {
  Serial.println("Message received:");
  Serial.println(command);
  return 0;
}
```

Here are some tests I ran using `curl 7.42.0`.

Here's the trailing `HTTP/`:

```
$ curl http://192.168.1.14/print?params=hello
{"return_value": 0, "id": "001", "name": "test", "connected": true}
```

```
Message received:
hello HTTP/
```

It seems that aRest just slices from the 7th character.

```
$ curl http://192.168.1.14/print?1234567
{"return_value": 0, "id": "001", "name": "test", "connected": true}
```

```
Message received:
 HTTP/
```

It's possible to get an entirely empty message by providing only 1 character in the query string:

```
$ curl http://192.168.1.14/print?1
{"return_value": 0, "id": "001", "name": "test", "connected": true}
```

```
Message received:

```

[2010]: http://www.freetronics.com.au/products/twentyten

**Comment by marcoschwartz** [comment] 2015-05-29 17:15
Got it now ! It's just because according to the aREST documentation, you need to use ?params= before giving the arguments :) From the doc:

/led?params=0 executes the function

So you would need to do:

curl http://192.168.1.14/print?params=1234567

**Comment by michaelsproul** [comment] 2015-05-29 22:05
@marcoschwartz: It's more than that, note the trailing ` HTTP/` in my first example. Also, requiring the string to be called params but not checking that strikes me as somewhat fragile (which is what my latter examples demonstrate).

**Comment by marcoschwartz** [comment] 2015-06-02 17:21
Hello,

I just tried again with my UNO + Ethernet shield, couldn't reproduce the trailing HTTP error. Can you try with the latest revision of the library ?

**Comment by marcoschwartz** [comment] 2015-12-03 16:34
This is now fixed :)

**Closed by marcoschwartz** 2015-12-03 16:34 UTC
Labels: bug
